### ISSUE TITLE
[feature request] circular scrolling

### ISSUE THREAD

**Issue by chris-kruining** [argyleink/ScrollSnapExplainers#18]
would it be possible for this to also properly support circular scrolling?

I have 2 use cases where this would be mighty handy:

1. image slider/carousel
2. virtual scrolling; for performance optimization in large list (in this case I want this for my webcomponents library, updating large lists of data is VERY costly because of all the DOM updates, and virtual scrolling would fix that)

**Comment by argyleink** [comment]
- we're definitely tracking the concept of `overflow-x: cyclical` in a similar way as these efforts are tracking scroll-snap
- we're also tracking [virtual scrolling](https://web.dev/2021-scroll-survey-report/#features)! 

i appreciate you sharing things you need from scrolling 🙂  i'll add this feature request to a document where I'm tracking developers needed more scroll powers. but i'm going to close it too, since these snap explainers arent around overflow. hope that's cool!
